//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ErrorMessage {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorMessage() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.ErrorMessage", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chưa đến thời điểm nhập báo cáo.
        /// </summary>
        internal static string CHUA_DEN_THOI_DIEM {
            get {
                return ResourceManager.GetString("CHUA_DEN_THOI_DIEM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chưa đến thời điểm nhập báo cáo !.
        /// </summary>
        internal static string LICH_NHAP_CHUA_DEN_THOI_DIEM {
            get {
                return ResourceManager.GetString("LICH_NHAP_CHUA_DEN_THOI_DIEM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đang tồn tại 1 lịch nhập liệu đang hoạt động !.
        /// </summary>
        internal static string LICH_NHAP_EXITS {
            get {
                return ResourceManager.GetString("LICH_NHAP_EXITS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lịch nhập liệu đã dừng hoạt động !.
        /// </summary>
        internal static string LICH_NHAP_KHONG_HOAT_DONG {
            get {
                return ResourceManager.GetString("LICH_NHAP_KHONG_HOAT_DONG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không tìm thấy lịch nhập liệu cho báo cáo !.
        /// </summary>
        internal static string LICH_NHAP_NOT_FOUND {
            get {
                return ResourceManager.GetString("LICH_NHAP_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đã quá hạn nhập báo cáo !.
        /// </summary>
        internal static string LICH_NHAP_QUA_HAN {
            get {
                return ResourceManager.GetString("LICH_NHAP_QUA_HAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn không có quyền cập nhật dữ liệu ở mục này !.
        /// </summary>
        internal static string UPDATE_NOT_PERMISSION {
            get {
                return ResourceManager.GetString("UPDATE_NOT_PERMISSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn không có quyền truy cập chức năng này !.
        /// </summary>
        internal static string VIEW_NOT_PERMISSION {
            get {
                return ResourceManager.GetString("VIEW_NOT_PERMISSION", resourceCulture);
            }
        }
    }
}
