//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace S4T_HaTinh.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class AspNetRoles
    {
        [Display(Name = "Mã vai trò")]
        public string Id { get; set; }

        [Display(Name = "Từ khóa")]
        public string Name { get; set; }

        [Display(Name = "Tên hiển thị")]
        public string TenHienThi { get; set; }

        [Display(Name = "Trạng thái")]
        public int TrangThai { get; set; }

        [Display(Name = "Nhóm đối tượng")]
        public Nullable<int> NhomDoiTuong_ID { get; set; }
    }
}
