//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace S4T_HaTinh.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using S4T_HaTinh.App_GlobalResources;
    
    public partial class CongNghiepCNTT
    {
        [Key]
        public int CongNghiepCNTT_ID { get; set; }
        public int DonVi_ID { get; set; }
        [Required(AllowEmptyStrings = false,ErrorMessageResourceType = typeof(ModelBinders), ErrorMessageResourceName = "PropertyValueRequired")]
        [StringLength(500)]
        public string FileUpload { get; set; }

        [DisplayFormat(DataFormatString = "{0:0.##}", ApplyFormatInEditMode = true)]
        [Range(typeof(decimal), "0", "79228162514264337593543950335",ErrorMessageResourceType = typeof(ModelBinders), ErrorMessageResourceName = "FieldMustBeNumeric")]
        public decimal DoanhThu { get; set; }
        public int SoMayTinh { get; set; }
        public int SoPhanMemUngDung { get; set; }
        public int SoWebsite { get; set; }
        public int SoMayTinhKetNoiMang { get; set; }

        [DataType(DataType.DateTime, ErrorMessageResourceType = typeof(ModelBinders), ErrorMessageResourceName = "FieldMustBeDate")]
        public System.DateTime TuNgay { get; set; }

        [DataType(DataType.DateTime, ErrorMessageResourceType = typeof(ModelBinders), ErrorMessageResourceName = "FieldMustBeDate")]
        public System.DateTime DenNgay { get; set; }

        [DataType(DataType.DateTime, ErrorMessageResourceType = typeof(ModelBinders), ErrorMessageResourceName = "FieldMustBeDate")]
        public System.DateTime NgayTao { get; set; }

        [DataType(DataType.DateTime, ErrorMessageResourceType = typeof(ModelBinders), ErrorMessageResourceName = "FieldMustBeDate")]
        public System.DateTime NgayCapNhat { get; set; }


        public byte Success { get; set; }
        public string TruongNhapLai { get; set; }
        public int LichNhap_ID { get; set; }
    }
}
