//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace S4T_HaTinh.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Dm_LoaiDuAn
    {
        [Key]
        [Display(Name = "Mã dự án")]
        public int LoaiDuAn_ID { get; set; }

        [Display(Name = "Tên dự án")]
        public string TenLoaiDuAn { get; set; }

        [Display(Name = "Số ngày giải quyết")]
        public int SoNgayGiaiQuyet { get; set; }

        [Display(Name = "Trạng thái")]
        public byte TrangThai { get; set; }
    }
}
