//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace S4T_HaTinh.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using S4T_HaTinh.App_GlobalResources;
    
    public partial class Dm_LoaiDanhMuc
    {
        [Key]
        [Display(Name = "Mã loại danh mục")]
        public int LoaiDanhMuc_ID { get; set; }
        
        [Required(AllowEmptyStrings = false,ErrorMessageResourceType = typeof(ModelBinders), ErrorMessageResourceName = "PropertyValueRequired")]
        [StringLength(250, ErrorMessageResourceType = typeof(ModelBinders), ErrorMessageResourceName = "PropertyValueOutOfRange")]
        [Display(Name = "Tên loại")]
        public string TenLoai { get; set; }

        [Required(AllowEmptyStrings = false,ErrorMessageResourceType = typeof(ModelBinders), ErrorMessageResourceName = "PropertyValueRequired")]
        [Display(Name = "Trạng thái")]
        public int TrangThai { get; set; }
    }
}
