//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace S4T_HaTinh.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using S4T_HaTinh.App_GlobalResources;
    
    public partial class Dm_ThongTinDonVi
    {
        [Key]
        public int ThongTin_ID { get; set; }
        public int DonVi_ID { get; set; }

        [Required(AllowEmptyStrings = false, ErrorMessageResourceType = typeof(ModelBinders), ErrorMessageResourceName = "PropertyValueRequired")]
        [Display(Name = "Tên cơ quan")]
        public string TenDonVi { get; set; }
        
        //[DefaultValue(0)]
        [Display(Name="Năm thành lập")]
        public Nullable<int> NamThanhLap { get; set; }

        [Display(Name = "Địa chỉ")]
        public string DiaChi { get; set; }

        [Display(Name = "Số điện thoại")]
        public string DienThoai { get; set; }

        [EmailAddress(ErrorMessage = "Phải nhập email đúng định dạng")]
        [Display(Name = "Email")]
        public string Email { get; set; }

        [Display(Name = "Website")]
        public string Website { get; set; }

        [Display(Name = "Giám đốc/Thủ trưởng")]
        public string GiamDoc { get; set; }

        [Display(Name = "Phó Giám Đốc 1")]
        public string PhoGiamDoc1 { get; set; }

        [Display(Name = "Phó Giám Đốc 2")]
        public string PhoGiamDoc2 { get; set; }

        [Display(Name = "Phó Giám Đốc 3")]
        public string PhoGiamDoc3 { get; set; }

        [Display(Name = "Phó Giám Đốc 4")]
        public string PhoGiamDoc4 { get; set; }

        [Display(Name = "Phó Giám Đốc 5")]
        public string PhoGiamDoc5 { get; set; }

        [Display(Name = "Phó Giám Đốc 6")]
        public string PhoGiamDoc6 { get; set; }

        [Display(Name = "Phó Giám Đốc 7")]
        public string PhoGiamDoc7 { get; set; }

        // Giám đốc CNTT
        [Display(Name="Họ tên")]
        public string Ten_GiamDocCNTT { get; set; }

        [Display(Name = "Điện thoại")]
        public string DienThoai_GiamDocCNTT { get; set; }

        [EmailAddress(ErrorMessage = "Phải nhập email đúng định dạng")]
        [Display(Name = "Email")]
        public string Email_GiamDocCNTT { get; set; }

        // Chánh văn phòng
        [Display(Name = "Họ tên")]
        public string Ten_ChanhVanPhong { get; set; }

        [Display(Name = "Điện thoại")]
        public string DienThoai_ChanhVanPhong { get; set; }

        [EmailAddress(ErrorMessage = "Phải nhập email đúng định dạng")]
        [Display(Name = "Email")]
        public string Email_ChanhVanPhong { get; set; }

        // Trưởng phòng văn hóa thông tin
        [Display(Name = "Họ tên")]
        public string Ten_TruongPhongVHTT { get; set; }

        [Display(Name = "Điện thoại")]
        public string DienThoai_TruongPhongVHTT { get; set; }

        [EmailAddress(ErrorMessage = "Phải nhập email đúng định dạng")]
        [Display(Name = "Email")]
        public string Email_TruongPhongVHTT { get; set; }

        // Phó phòng văn hóa thông tin
        [Display(Name = "Họ tên")]
        public string Ten_PhoPhongVHTT { get; set; }

        [Display(Name = "Điện thoại")]
        public string DienThoai_PhoPhongVHTT { get; set; }

        [EmailAddress(ErrorMessage = "Phải nhập email đúng định dạng")]
        [Display(Name = "Email")]
        public string Email_PhoPhongVHTT { get; set; }

        [DefaultValue(0)]
        [Display(Name = "Số lượng CBCC")]
        public Nullable<int> SoCBCC { get; set; }

        [DefaultValue(0)]
        [Display(Name = "Số đơn vị trực thuộc")]
        public Nullable<int> SoDonViTrucThuoc { get; set; }

        [DefaultValue(0)]
        [Display(Name = "Tổng số CBCNV tại các đơn vị trực thuộc")]
        public Nullable<int> SoCB_DVTT { get; set; }

        [Display(Name = "Phòng/Trung tâm CNTT")]
        public Nullable<byte> HasPhongCNTT { get; set; }

        [DefaultValue(0)]
        [Display(Name = "Số lượng CB thuộc phòng/Trung tâm CNTT")]
        public Nullable<int> SoCB_PhongCNTT { get; set; }

        [Display(Name = "Tổ CNTT")]
        public Nullable<byte> HasToCNTT { get; set; }

        [DefaultValue(0)]
        [Display(Name = "Số lượng CB thuộc tổ CNTT")]
        public Nullable<int> SoCB_ToCNTT { get; set; }

        [DefaultValue(0)]
        [Display(Name = "Tổng diện tích (km2)")]
        public Nullable<int> TongDienTich { get; set; }

        [DefaultValue(0)]
        [Display(Name = "Tổng số xã/ phường/ thị trấn")]
        public Nullable<int> TongSoXa { get; set; }

        [DefaultValue(0)]
        [Display(Name = "Tổng số hộ gia đình")]
        public Nullable<int> TongSoHoGiaDinh { get; set; }

        [DefaultValue(0)]
        [Display(Name = "Tổng dân số")]
        public Nullable<int> TongDanSo { get; set; }

        [Display(Name = "Tổng số cán bộ công chức tại các UBND xã")]
        public Nullable<int> SoCBCC_Xa { get; set; }

        [DefaultValue(0)]
        [Display(Name = "Số trường mầm non")]
        public Nullable<int> SoTruongMamNon { get; set; }

        [DefaultValue(0)]
        [Display(Name = "Số trường Tiểu học")]
        public Nullable<int> SoTruongTieuHoc { get; set; }

        [DefaultValue(0)]
        [Display(Name = "Số trường THCS")]
        public Nullable<int> SoTruongTHCS { get; set; }

        [DefaultValue(0)]
        [Display(Name = "Số trường THPT")]
        public Nullable<int> SoTruongTHPT { get; set; }

        [DefaultValue(0)]
        [Display(Name = "Số Trung tâm Giáo dục thường xuyên")]
        public Nullable<int> SoTrungTamGDTX { get; set; }

        [DefaultValue(0)]
        [Display(Name = "Số trường Dạy nghề")]
        public Nullable<int> SoTruongDayNghe { get; set; }

        [DefaultValue(0)]
        [Display(Name = "Số trường Trung cấp")]
        public Nullable<int> SoTruongTrungCap { get; set; }

        [Display(Name = "Số trường Cao đẳng")]
        public Nullable<int> SoTruongCaoDang { get; set; }

        [DefaultValue(0)]
        [Display(Name = "Số trường Đại học")]
        public Nullable<int> SoTruongDaiHoc { get; set; }

        [DefaultValue(0)]
        [Display(Name = "Số trạm Y tế")]
        public Nullable<int> SoTramYTe { get; set; }

        [DefaultValue(0)]
        [Display(Name = "Số Trung tâm Y tế dự phòng")]
        public Nullable<int> SoTrungTamYTeDuPhong { get; set; }

        [DefaultValue(0)]
        [Display(Name = "Số Bệnh viện")]
        public Nullable<int> SoBenhVien { get; set; }

        [DefaultValue(0)]
        [Display(Name = "Số doanh nghiệp về lĩnh vực CNTT – Điện tử")]
        public Nullable<int> SoDoanhNghiepCNTT { get; set; }

        [DefaultValue(0)]
        [Display(Name = "Số lao động về lĩnh vực CNTT – Điện tử")]
        public Nullable<int> SoNVCNTT { get; set; }

        [DefaultValue(0)]
        [Display(Name = "Tổng số hợp tác xã")]
        public Nullable<int> SoHopTacXa { get; set; }

        [DefaultValue(0)]
        [Display(Name = "Tổng số làng nghề truyền thống")]
        public Nullable<int> SoLangNgheTruyenThong { get; set; }

        // Cán bộ chuyên trách 1
        [Display(Name = "Họ tên")]
        public string HoTen_CBCT1 { get; set; }

        [Display(Name = "Ngày sinh")]
        public Nullable<System.DateTime> NgaySinh_CBCT1 { get; set; }

        [Display(Name = "Số điện thoại")]
        public string DienThoai_CBCT1 { get; set; }

        [Display(Name = "Trình độ về CNTT")]
        public Nullable<int> TrinhDoCNTT_CBCT1 { get; set; }

        [EmailAddress(ErrorMessage = "Phải nhập email đúng định dạng")]
        [Display(Name = "Email")]
        public string Email_CBCT1 { get; set; }

        // Cán bộ chuyên trách 2
        [Display(Name = "Họ tên")]
        public string HoTen_CBCT2 { get; set; }

        [Display(Name = "Ngày sinh")]
        public Nullable<System.DateTime> NgaySinh_CBCT2 { get; set; }

        [Display(Name = "Số điện thoại")]
        public string DienThoai_CBCT2 { get; set; }

        [Display(Name = "Trình độ về CNTT")]
        public Nullable<int> TrinhDoCNTT_CBCT2 { get; set; }

        [EmailAddress(ErrorMessage = "Phải nhập email đúng định dạng")]
        [Display(Name = "Email")]
        public string Email_CBCT2 { get; set; }
    }
}
