//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace S4T_HaTinh.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EditUserViewModels
    {
        public string UserName { get; set; }
        public string HoVaTen { get; set; }
        public int DonVi_ID { get; set; }
        public string Email { get; set; }
        public int TrangThai { get; set; }
    }
}
