//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace S4T_HaTinh.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using S4T_HaTinh.App_GlobalResources;

    public partial class HaTangKyThuatCNTT
    {
        [Key]
        public int HaTangKyThuatCNTT_ID { get; set; }

        [Display(Name = "Đơn vị")]
        public int DonVi_ID { get; set; }

        public int LichNhap_ID { get; set; }

        [Display(Name = "Máy tính để bàn tại đơn vi")]
        //[Range(0,decimal int.MaxValue, ErrorMessageResourceType = typeof(ModelBinders), ErrorMessageResourceName = "FieldMustBeNumeric")]
        public int MayBan { get; set; }

        [Display(Name = "LapTop tại đơn vị")]
        public int LapTop { get; set; }

        [Display(Name = "Máy chủ tại đơn vị")]
        public int MayChu { get; set; }

        [Display(Name = "Số máy kết nối Internet tại đơn vị")]
        public int MayNoiMangInternet { get; set; }

        [Display(Name = "Phần mềm virus có bản quyền")]
        public int VirusCoBanQuyen { get; set; }

        [Display(Name = "Số máy chiếu")]
        public int MayChieu { get; set; }

        [Display(Name = "Số máy scan")]
        public int MayScan { get; set; }

        [Display(Name = "Số máy in")]
        public int MayIn { get; set; }

        [Display(Name = "Số máy ảnh")]
        public int MayAnh { get; set; }

        [Display(Name = "Số máy quay phim")]
        public int MayQuayPhim { get; set; }

        [Display(Name = "Số máy tính bảng")]
        public int MayTinhBang { get; set; }

        [Display(Name = "Máy bàn tại đơn vị trực thuộc")]
        public int MayBan_DVTT { get; set; }

        [Display(Name = "Laptop tại đơn vị trực thuộc")]
        public int LapTop_DVTT { get; set; }

        [Display(Name = "Máy chủ tại đơn vị trực thuộc")]
        public int MayChu_DVTT { get; set; }

        [Display(Name = "Số máy kết nối mạng Internet tại đơn vị trực thuộc")]
        public int MayNoiMangInternet_DVTT { get; set; }

        [Display(Name = "Phần mềm virus có bản quyền tại đơn vị trực thuộc")]
        public int VirusCoBanQuyen_DVTT { get; set; }

        [Display(Name = "Số máy chiếu tại đơn vị trực thuộc")]
        public int MayChieu_DVTT { get; set; }

        [Display(Name = "Số máy scan tại đơn vị trực thuộc")]
        public int MayScan_DVTT { get; set; }

        [Display(Name = "Số máy in tại đơn vị trực thuộc")]
        public int MayIn_DVTT { get; set; }

        [Display(Name = "Số máy ảnh tại đơn vị trực thuộc")]
        public int MayAnh_DVTT { get; set; }

        [Display(Name = "Số máy quay phim tại đơn vị trực thuộc")]
        public int MayQuayPhim_DVTT { get; set; }

        [Display(Name = "Số máy tính bảng tại đơn vị trực thuộc")]
        public int MayTinhBang_DVTT { get; set; }

        [Display(Name = "Phòng họp trực tuyến")]
        public byte PhongHopTrucTuyen { get; set; }

        [Display(Name = "Số ADSL")]
        public int ADSL { get; set; }

        [Display(Name = "Số Cáp Quang")]
        public int CapQuang { get; set; }

        [Display(Name = "Số Leased line")]
        public int LeasedLine { get; set; }

        [Display(Name = "Số Mạng chuyên dụng")]
        public int MangChuyenDung { get; set; }

        [Display(Name = "Dung lượng ADSL ")]
        public int DungLuong_ADSL { get; set; }

        [Display(Name = "Dung lượng Cáp quang")]
        public int DungLuong_CapQuang { get; set; }

        [Display(Name = "Dung lượng Leased line")]
        public int DungLuong_Leased { get; set; }

        [Display(Name = "Dung lượng Mạng chuyên dụng")]
        public int DungLuong_MangChuyenDung { get; set; }

        [Display(Name = "Màn hình hiển thị lịch công tác:")]
        public int ManHinh_LichCongTac { get; set; }

        [Display(Name = "Màn hình tra cứu thủ tục hành chính")]
        public int ManHinh_TraCuuTTHC { get; set; }

        [Display(Name = "Có tường lửa")]
        public byte HeThongTuongLua { get; set; }

        [Display(Name = "Có hệ thống phát hiện và phòng, chống truy cập trái phép")]
        public byte PhongChongTruyCapTraiPhep { get; set; }

        [Display(Name = "Có cảnh báo cháy, nổ tại phòng máy chủ")]
        public byte CanhBaoChayNo { get; set; }

        [Display(Name = "Có chống sét tại phòng máy chủ")]
        public byte ChongSet { get; set; }

        [Display(Name = "Băng từ")]
        public byte BangTu { get; set; }

        [Display(Name = "Tủ đĩa")]
        public byte TuDia { get; set; }

        [Display(Name = "SAN")]
        public byte SAN { get; set; }

        [Display(Name = "NAS")]
        public byte NAS { get; set; }

        [Display(Name = "DAS")]
        public byte DAS { get; set; }

        [Display(Name = "RAID")]
        public byte RAID { get; set; }

        [Display(Name = "Khác")]
        public byte Khac { get; set; }

        [Display(Name = "Tổng mức đầu tư")]
        public decimal TongMucDauTu { get; set; }

        [Display(Name = "Trạng thái")]
        public byte Success { get; set; }

        [Display(Name = "Trường nhập lại")]
        public string TruongNhapLai { get; set; }
    }
}
