//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace S4T_HaTinh.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using S4T_HaTinh.App_GlobalResources;
    using DataAnnotationsExtensions;

    public partial class HaTangNhanLucCNTT
    {
        [Key]
        public int HaTangNhanLucCNTT_ID { get; set; }

        [Display(Name = "Đơn vị")]
        public int DonVi_ID { get; set; }

        public int LichNhap_ID { get; set; }

        [Range(0, 1000000000,
            ErrorMessageResourceType = typeof(ModelBinders), ErrorMessageResourceName = "IntegerOutOfRange")]
        [Display(Name = "Số Tiến sỹ tại đơn vị")]
        public int TienSy_DV { get; set; }

        [Range(0, 1000000000,
            ErrorMessageResourceType = typeof(ModelBinders), ErrorMessageResourceName = "IntegerOutOfRange")]
        [Display(Name = "Số Thạc sỹ tại đơn vị")]
        public int ThacSy_DV { get; set; }

        [Range(0, 1000000000,
            ErrorMessageResourceType = typeof(ModelBinders), ErrorMessageResourceName = "IntegerOutOfRange")]
        [Display(Name = "Số Đại học chính quy tại đơn vị")]
        public int DaiHocChinhQuy_DV { get; set; }

        [Range(0, 1000000000,
            ErrorMessageResourceType = typeof(ModelBinders), ErrorMessageResourceName = "IntegerOutOfRange")]
        [Display(Name = "Số Đại học không chính quy tại đơn vị")]
        public int DaiHocKhongChinhQuy_DV { get; set; }

        [Range(0, 1000000000,
            ErrorMessageResourceType = typeof(ModelBinders), ErrorMessageResourceName = "IntegerOutOfRange")]
        [Display(Name = "Số lượt tập huấn tại đơn vị")]
        public int LuotTapHuan_DV { get; set; }

        [Range(0, 1000000000,
            ErrorMessageResourceType = typeof(ModelBinders), ErrorMessageResourceName = "IntegerOutOfRange")]
        [Display(Name = "Số lượng cán bộ tại đơn vị")]
        public int SoLuongCanBo_DV { get; set; }

        [Range(0, 1000000000,
            ErrorMessageResourceType = typeof(ModelBinders), ErrorMessageResourceName = "IntegerOutOfRange")]
        [Display(Name = "Số Tiến sỹ tại đơn vị trực thuộc")]
        public int TienSy_DVTT { get; set; }

        [Range(0, 1000000000,
            ErrorMessageResourceType = typeof(ModelBinders), ErrorMessageResourceName = "IntegerOutOfRange")]
        [Display(Name = "Số Thạc sỹ tại đơn vị trực thuộc")]
        public int ThacSy_DVTT { get; set; }

        [Range(0, 1000000000,
            ErrorMessageResourceType = typeof(ModelBinders), ErrorMessageResourceName = "IntegerOutOfRange")]
        [Display(Name = "Số Đại học chính quy tại đơn vị trực thuộc")]
        public int DaiHocChinhQuy_DVTT { get; set; }

        [Range(0, 1000000000,
            ErrorMessageResourceType = typeof(ModelBinders), ErrorMessageResourceName = "IntegerOutOfRange")]
        [Display(Name = "Số Đại học không chính quy tại đơn vị trực thuộc")]
        public int DaiHocKhongChinhQuy_DVTT { get; set; }

        [Range(0, 1000000000,
            ErrorMessageResourceType = typeof(ModelBinders), ErrorMessageResourceName = "IntegerOutOfRange")]
        [Display(Name = "Số lượt tập huấn tại đơn vị trực thuộc")]
        public int LuotTapHuan_DVTT { get; set; }

        [Range(0, 1000000000,
            ErrorMessageResourceType = typeof(ModelBinders), ErrorMessageResourceName = "IntegerOutOfRange")]
        [Display(Name = "Số lượng cán bộ tại đơn vị trực thuộc")]
        public int SoLuongCanBo_DVTT { get; set; }

        [Range(0, 1000000000,
            ErrorMessageResourceType = typeof(ModelBinders), ErrorMessageResourceName = "IntegerOutOfRange")]
        [Display(Name = "Số cán bộ sử dụng thành thạo máy tính tại cơ quan")]
        public int ThanhThaoMayTinh_DV { get; set; }

        [Range(0, 1000000000,
            ErrorMessageResourceType = typeof(ModelBinders), ErrorMessageResourceName = "IntegerOutOfRange")]
        [Display(Name = "Số lượt tập huấn thành thạo máy tính tại cơ quan")]
        public int LuotTapHuanThanhThaoMayTinh_DV { get; set; }

        [Range(0, 1000000000,
            ErrorMessageResourceType = typeof(ModelBinders), ErrorMessageResourceName = "IntegerOutOfRange")]
        [Display(Name = "Số cán bộ sử dụng thành thạo máy tính tại đơn vị cấp 2")]
        public int ThanhThaoMayTinh_DVTT { get; set; }

        [Range(0, 1000000000,
            ErrorMessageResourceType = typeof(ModelBinders), ErrorMessageResourceName = "IntegerOutOfRange")]
        [Display(Name = "Số lượt tập huấn thành thạo máy tính tại đơn vị cấp 2")]
        public int LuotTapHuanThanhThaoMayTinh_DVTT { get; set; }

        [Display(Name = "Tổng mức đầu tư")]
        public decimal TongMucDauTu { get; set; }

        [Display(Name = "Trạng thái")]
        public byte Success { get; set; }

        [Display(Name = "Trường nhập lại")]
        public string TruongNhapLai { get; set; }
    }
}
