//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace S4T_HaTinh.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using S4T_HaTinh.App_GlobalResources;

    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;

    public partial class HaTangKyThuatCNTT_Huyen
    {
        [Key]
        public int HaTangKyThuatCNTTHuyen_ID { get; set; }

        public int LichNhap_ID { get; set; }

        [Display(Name = "Đơn vị")]
        public int DonVi_ID { get; set; }

        [Display(Name = "ADSL")]
        public int ADSL { get; set; }

        [Display(Name = "Cáp quang")]
        public int CapQuang { get; set; }

        [Display(Name = "Khác")]
        public int Khac { get; set; }

        [Display(Name = "LeadedLine")]
        public int LeadedLine { get; set; }

        [Display(Name = "Máy tính để bàn của UBND Huyện")]
        public int UBND_MayBan { get; set; }

        [Display(Name = "Máy laptop của UBND Huyện")]
        public int UBND_LapTop { get; set; }

        [Display(Name = "Máy chủ của UBND Huyện")]
        public int UBND_MayChu { get; set; }

        [Display(Name = "Máy tính sử dụng phần mềm virut bản quyền của UBND Huyện")]
        public int UBND_VirusBanQuyen { get; set; }

        [Display(Name = "Máy tính có kết nối mạng Internet của UBND Huyện")]
        public int UBND_Internet { get; set; }

        [Display(Name = "Máy tính có kết nối mạng CD của UBND Huyện")]
        public int UBND_MangCD { get; set; }

        [Display(Name = "Máy tính để bàn bàn của cấp Huyện Ủy")]
        public int HuyenUy_MayBan { get; set; }

        [Display(Name = "Máy laptop của cấp Huyện Ủy")]
        public int HuyenUy_LapTop { get; set; }

        [Display(Name = "Máy chủ của cấp Huyện Ủy")]
        public int HuyenUy_MayChu { get; set; }

        [Display(Name = "Máy tính sử dụng phần mềm virut bản quyền của cấp Huyện Ủy")]
        public int HuyenUy_VirusBanQuyen { get; set; }

        [Display(Name = "Máy tính có kết nối mạng Internet  của cấp Huyện Ủy")]
        public int HuyenUy_Internet { get; set; }

        [Display(Name = "Máy tính có kết nối mạng CD của cấp Huyện Ủy")]
        public int HuyenUy_MangCD { get; set; }

        [Display(Name = "Máy tính để bàn của Cấp Xã")]
        public int Xa_MayBan { get; set; }

        [Display(Name = "Máy laptop của Cấp Xã")]
        public int Xa_LapTop { get; set; }

        [Display(Name = "Máy chủ của Cấp Xã")]
        public int Xa_MayChu { get; set; }

        [Display(Name = "Máy tính sử dụng phần mềm virut bản quyền của Cấp Xã")]
        public int Xa_VirusBanQuyen { get; set; }

        [Display(Name = "Máy tính có kết nối mạng Internet của Cấp Xã")]
        public int Xa_Internet { get; set; }

        [Display(Name = "Máy tính có kết nối mạng CD của Cấp Xã")]
        public int Xa_MangCD { get; set; }

        [Display(Name = "Máy tính để bàn của Giáo dục")]
        public int GiaoDuc_MayBan { get; set; }

        [Display(Name = "Máy laptop của Giáo dục")]
        public int GiaoDuc_LapTop { get; set; }

        [Display(Name = "Máy chủ của Giáo dục")]
        public int GiaoDuc_MayChu { get; set; }

        [Display(Name = "Máy tính sử dụng phần mềm virut bản quyền của Giáo dục")]
        public int GiaoDuc_VirusBanQuyen { get; set; }

        [Display(Name = "Máy tính có kết nối mạng Internet của Giáo dục")]
        public int GiaoDuc_Internet { get; set; }

        [Display(Name = "Máy tính có kết nối mạng CD của Giáo dục")]
        public int GiaoDuc_MangCD { get; set; }

        [Display(Name = "Máy tính để bàn của Y Tế")]
        public int YTe_MayBan { get; set; }

        [Display(Name = "Máy laptop của Y Tế")]
        public int YTe_LapTop { get; set; }

        [Display(Name = "Máy Chủ của Y Tế")]
        public int YTe_MayChu { get; set; }

        [Display(Name = "Máy tính sử dụng phần mềm virut bản quyền của Y Tế")]
        public int YTe_VirusBanQuyen { get; set; }

        [Display(Name = "Máy tính có kết nối mạng Internet của Y Tế")]
        public int YTe_Internet { get; set; }

        [Display(Name = "Máy tính có kết nối mạng CD của Y Tế")]
        public int YTe_MangCD { get; set; }

        [Display(Name = "Máy tính để bàn Khác")]
        public int Khac_MayBan { get; set; }

        [Display(Name = "Máy laptop Khác")]
        public int Khac_LapTop { get; set; }

        [Display(Name = "Máy Chủ Khác")]
        public int Khac_MayChu { get; set; }

        [Display(Name = "Máy tính sử dụng phần mềm virut bản quyền Khác")]
        public int Khac_VirusBanQuyen { get; set; }

        [Display(Name = "Máy tính có kết nối mạng Internet Khác")]
        public int Khac_Internet { get; set; }

        [Display(Name = "Máy tính có kết nối mạng CD Khác")]
        public int Khac_MangCD { get; set; }

        [Display(Name = "Máy tính để bàn của Văn Hóa Xã")]
        public int VHX_MayBan { get; set; }

        [Display(Name = "Máy laptop của Văn Hóa Xã")]
        public int VHX_LapTop { get; set; }

        [Display(Name = "Máy chủ của Văn Hóa Xã")]
        public int VHX_MayChu { get; set; }

        [Display(Name = "Máy tính sử dụng phần mềm virut bản quyền của Văn Hóa Xã")]
        public int VHX_VirusBanQuyen { get; set; }

        [Display(Name = "Máy tính có kết nối mạng Internet của Văn Hóa Xã")]
        public int VHX_Internet { get; set; }

        [Display(Name = "Máy tính có kết nối mạng CD của Văn Hóa Xã")]
        public int VHX_MangCD { get; set; }

        [Display(Name = "Máy tính để bàn của Doanh Nghiệp")]
        public int DoanhNghiep_MayBan { get; set; }

        [Display(Name = "Máy laptop của Doanh Nghiệp")]
        public int DoanhNghiep_LapTop { get; set; }

        [Display(Name = "Máy chủ của Doanh Nghiệp")]
        public int DoanhNghiep_MayChu { get; set; }

        [Display(Name = "Máy tính sử dụng phần mềm virut bản quyền của Doanh Nghiệp")]
        public int DoanhNghiep_VirusBanQuyen { get; set; }

        [Display(Name = "Máy tính có kết nối mạng Internet của Doanh Nghiệp")]
        public int DoanhNghiep_Internet { get; set; }

        [Display(Name = "Máy tính có kết nối mạng CD của Doanh Nghiệp")]
        public int DoanhNghiep_MangCD { get; set; }

        [Display(Name = "Hộ gia đình máy tính bàn")]
        public int HoGiaDinh_MayBan { get; set; }

        [Display(Name = "Hộ gia đình laptop")]
        public int HoGiaDinh_LapTop { get; set; }

        [Display(Name = "Hộ gia đình máy chủ")]
        public int HoGiaDinh_MayChu { get; set; }

        [Display(Name = "Hộ gia đình virus bản quyền")]
        public int HoGiaDinh_VirusBanQuyen { get; set; }

        [Display(Name = "Hộ gia đình kết nối internet")]
        public int HoGiaDinh_Internet { get; set; }

        [Display(Name = "Hộ gia đình kết nối mạng CD")]
        public int HoGiaDinh_MangCD { get; set; }

        [Display(Name = "Số máy tính không kết nối Internet vì lý do an ninh")]
        public int KhongKetNoiInternet { get; set; }

        [Display(Name = "Tường lửa")]
        public byte TuongLua { get; set; }

        [Display(Name = "Truy cập trái phép")]
        public byte TruyCapTraiPhep { get; set; }

        [Display(Name = "Cảnh báo cháy nổ")]
        public byte CanhBaoChayNo { get; set; }

        [Display(Name = "Chống sét")]
        public byte ChongSet { get; set; }

        [Display(Name = "Băng từ")]
        public byte BangTu { get; set; }

        [Display(Name = "Tủ đĩa")]
        public byte TuDia { get; set; }

        [Display(Name = "SAN")]
        public byte SAN { get; set; }

        [Display(Name = "NAS")]
        public byte NAS { get; set; }

        [Display(Name = "DAS")]
        public byte DAS { get; set; }

        [Display(Name = "RAID")]
        public byte RAID { get; set; }

        [Display(Name = "Số điểm bưu điện văn hóa xã")]
        public int BuuDienXa { get; set; }

        [Display(Name = "Số điểm bưu điện văn hóa xã có Internet")]
        public int BuuDienXa_Internet { get; set; }

        [Display(Name = "Số điểm bưu điện văn hóa xã có đại lý Internet")]
        public int BuuDienXa_DaiLyInternet { get; set; }

        [Display(Name = "Hội nghị truyền hình cấp huyện")]
        public byte HoiNghiTruyenHinhCapHuyen { get; set; }

        [Display(Name = "Số cuộc họp của cấp huyện – tỉnh/ năm")]
        public int SoCuocHopCapHuyen { get; set; }

        [Display(Name = "Hội nghị truyền hình cấp xã")]
        public byte HoiNghiTruyenHinhCapXa { get; set; }

        [Display(Name = "Số lượng Hội nghị truyền hình cấp xã")]
        public int SoHoiNghiTruyenHinhCapXa { get; set; }

        [Display(Name = "Số cuộc họp cấp xã – huyện/ năm")]
        public int SoCuocHopCapXa { get; set; }
        
        [Display(Name = "Tổng chi ngân sách cho hạ tầng kỹ thuật CNTT")]
        public decimal TongChiNganSach { get; set; }

        [Display(Name = "Tổng mức đầu tư")]
        public decimal TongMucDauTu { get; set; }

        [Display(Name = "Trường nhập lại")]
        public string TruongNhapLai { get; set; }

        [Display(Name = "Trạng Thái ")]
        public byte Success { get; set; }
    }
}
