//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace S4T_HaTinh.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using S4T_HaTinh.App_GlobalResources;
    
    public partial class Ht_FileDinhKem
    {
        [Key]
        public int FileUpload_ID { get; set; }
        public int BaoCao_ID { get; set; }
        public int PhanHeChucNang_ID { get; set; }
        public int DonVi_ID { get; set; }
        public int LoaiVanBan_ID { get; set; }

        [Display(Name="Số văn bản")]
        public string SoVanBan { get; set; }

        [Display(Name = "Trích yếu")]
        public string TrichYeu { get; set; }

        [Display(Name = "Ngày ban hành")]
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}", ApplyFormatInEditMode = true)]
        public Nullable<System.DateTime> NgayBanHanh { get; set; }
        public string DuongDan { get; set; }

        [Display(Name = "Tên file")]
        public string TenFile { get; set; }
        public string NguoiUpLoad { get; set; }
        
        public Nullable<System.DateTime> NgayUpload { get; set; }
        public byte HieuLuc { get; set; }
        public Nullable<byte> CheDoBaoCao { get; set; }
        public Nullable<byte> QuanTamCuaLanhDao { get; set; }
        public string GhiChu { get; set; }

        [Display(Name = "Tên hiển thị")]
        public string TenHienThi { get; set; }
        public byte TrangThai { get; set; }
    }
}
