//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace S4T_HaTinh.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Ht_FileHoSo_LoaiDuAn
    {
        [Key]
        public int LoaiFile_ID { get; set; }

        [Display(Name = "Mã loại dự án")]
        public Nullable<int> LoaiDuAn_ID { get; set; }

        [Display(Name = "Tên file")]
        public string TenFile { get; set; }

        [Display(Name = "Số bản chính")]
        public Nullable<int> SoBanChinh { get; set; }

        [Display(Name = "Số bản sao")]
        public Nullable<int> SoBanSao { get; set; }

        [Display(Name = "Số bản pho to")]
        public Nullable<int> SoBanPhoTo { get; set; }

        [Display(Name = "Ghi chú")]
        public string GhiChu { get; set; }

        [Display(Name = "Trạng thái")]
        public byte TrangThai { get; set; }
    }
}
