//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace S4T_HaTinh.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class HT_Log
    {
        [Key]
        public int Log_ID { get; set; }
        public int User_ID { get; set; }

        [Display(Name = "Chức năng")]
        public string ChucNang { get; set; }

        [Display(Name = "Thao tác")]
        public string ThaoTac { get; set; }

        [Display(Name = "Thời gian")]
        public System.DateTime ThoiGian { get; set; }

        [Display(Name = "Nội dung")]
        public string NoiDung { get; set; }
    }
}
