//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace S4T_HaTinh.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ht_MaxID
    {
        public string ColumnName { get; set; }
        public string TableName { get; set; }
        public int MaxValue { get; set; }
        public string GhiChu { get; set; }
    }
}
