//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace S4T_HaTinh.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Ht_Role_PhanHe_ChucNang
    {
        [Key]
        [Display(Name="Mã chức năng")]
        public int PhanHeChucNang_ID { get; set; }

        [Display(Name = "Chức năng")]
        public string TenChucNang { get; set; }

        [Display(Name = "Vai trò")]
        public string TenVaiTro { get; set; }

        [Display(Name = "Mã vai trò")]
        public string RoleId { get; set; }

        [Display(Name = "Quyền xem")]
        public Nullable<byte> IsView { get; set; }

        [Display(Name = "Quyền sửa")]
        public Nullable<byte> IsEdit { get; set; }
    }
}
