//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace S4T_HaTinh.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Ht_ThamSoHeThong
    {
        [Key]
        public int ThamSo_ID { get; set; }
        public Nullable<int> User_ID { get; set; }

        [Display(Name = "Tên tham số")]
        public string TenThamSo { get; set; }

        [Display(Name = "Mã tham số")]
        public string MaThamSo { get; set; }

        [Display(Name = "Giá trị tham số")]
        public string GiaTriThamSo { get; set; }

        [Display(Name = "Comment")]
        public string Comment { get; set; }
    }
}
