//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace S4T_HaTinh.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NhomVanBan
    {
        public int NhomVanBan_ID { get; set; }
        public string MaNhomVanBan { get; set; }
        public string TenNhomVanBan { get; set; }
        public string GhiChu { get; set; }
        public int TrangThai { get; set; }
        public int LoaiVanBan_ID { get; set; }
    }
}
