//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace S4T_HaTinh.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using S4T_HaTinh.App_GlobalResources;
    
    public partial class PhanMemQLCN
    {
        [Key]
        public int PhanMemQLCN_ID { get; set; }
        public int UngDungCNTT_ID { get; set; }
        public int PhanHe_ID { get; set; }
        public int DonVi_ID { get; set; }

        [Required(AllowEmptyStrings = false,ErrorMessageResourceType = typeof(ModelBinders), ErrorMessageResourceName = "PropertyValueRequired")]
        public string TenPhanMem { get; set; }
        public Nullable<int> SBN { get; set; }
        public Nullable<int> UBND_Huyen { get; set; }
        public Nullable<int> UBND_Xa { get; set; }
        public Nullable<int> DVTT { get; set; }
        public byte Success { get; set; }
        public string TruongNhapLai { get; set; }
    }
}
