//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace S4T_HaTinh.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class TD_CauHinh
    {
        [Key]
        public int CauHinh_ID { get; set; }

        [Display(Name = "Tên cấu hình")]
        public string TenCauHinh { get; set; }

        [Display(Name = "Mã cấu hình")]
        public string MaCauHinh { get; set; }

        [Display(Name = "Nội dung")]
        public string NoiDung { get; set; }

        [Display(Name = "Người sử dụng")]
        public string User_ID { get; set; }

        [Display(Name = "Dùng toàn cục")]
        public Nullable<byte> IsGlobal { get; set; }
    }
}
