//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace S4T_HaTinh.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web;

    public partial class TD_FileHoSoDinhKem
    {
        [Key]
        public int FileHoSoDinhKem_ID { get; set; }

        [Display(Name = "Ten file")]
        public string TenFile { get; set; }

        [Display(Name = "Tên hiển thị")]
        public string TenHienThi { get; set; }

        [Display(Name = "Đường dẫn")]
        public string DuongDan { get; set; }

        [Display(Name = "Ghi chú")]
        public string GhiChu { get; set; }

        [Display(Name = "Trạng thái")]
        public byte TrangThai { get; set; }

        [Display(Name = "Mã hồ sơ")]
        public string MaHoSo { get; set; }

        [Display(Name = "Tên văn bản")]
        public string TenVanBan { get; set; }

        [Display(Name = "Số thứ tự")]
        public Nullable<int> STT { get; set; }

        public int VanBan_ID { get; set; }

        [Display(Name = "Số ký hiệu")]
        public string SoKyHieu { get; set; }

        [Display(Name = "Trích yếu")]
        public string TrichYeu { get; set; }

        [Display(Name = "Ngày ban hành")]
        public Nullable<System.DateTime> NgayBanHanh { get; set; }
    }
}
