//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace S4T_HaTinh.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using S4T_HaTinh.App_GlobalResources;
    
    public partial class TinhHinhSXDN
    {
        [Key]
        public int TinhHinhSXDN_ID { get; set; }

        [Display(Name = "Tên đơn vị")]
        public int DonVi_ID { get; set; }

        [DisplayFormat(DataFormatString = "{0:0.##}", ApplyFormatInEditMode = true)]
        [Range(typeof(decimal), "0", "79228162514264337593543950335", ErrorMessageResourceType = typeof(ModelBinders), ErrorMessageResourceName = "FieldMustBeNumeric")]
        [Display(Name = "Doanh Thu")]
        public decimal DoanhThu { get; set; }

        [DisplayFormat(DataFormatString = "{0:0.##}", ApplyFormatInEditMode = true)]
        [Range(typeof(decimal), "0", "79228162514264337593543950335", ErrorMessageResourceType = typeof(ModelBinders), ErrorMessageResourceName = "FieldMustBeNumeric")]
        [Display(Name = "Nộp Thuế")]
        public decimal TienNopThue { get; set; }

        [DisplayFormat(DataFormatString = "{0:0.##}", ApplyFormatInEditMode = true)]
        [Range(typeof(decimal), "0", "79228162514264337593543950335", ErrorMessageResourceType = typeof(ModelBinders), ErrorMessageResourceName = "FieldMustBeNumeric")]
        [Display(Name = "Thu nhập TB Nhân viên")]
        public decimal ThuNhapTrungBinh { get; set; }

        [DisplayFormat(DataFormatString = "{0:0.##}", ApplyFormatInEditMode = true)]
        [Range(typeof(decimal), "0", "79228162514264337593543950335", ErrorMessageResourceType = typeof(ModelBinders), ErrorMessageResourceName = "FieldMustBeNumeric")]
        [Display(Name = "Đóng góp xã hội")]
        public decimal DongGopXaHoi { get; set; }

        [Display(Name = "Kiến Nghị và đề xuất")]
        public string KienNghi { get; set; }
        public string FileUpload { get; set; }

        [Display(Name = "Trạng Thái")]
        public byte Success { get; set; }
       
        public string TruongNhapLai { get; set; }

        [Display(Name = "Người đại diện")]
        public string NguoiDaiDien { get; set; }

        [Display(Name = "Nhân lực trong ngành CNTT Đại Học")]
        public int NLTN_DaiHoc { get; set; }

         [Display(Name = "Nhân lực trong ngành CNTT Cao Đẳng")]
        public int NLTN_CaoDang { get; set; }

         [Display(Name = "Nhân lực trong ngành CNTT Trung Cấp")]
        public int NLTN_TrungCap { get; set; }

         [Display(Name = "Nhân lực trong ngành CNTT Tiến sĩ")]
        public int NLTN_TienSi { get; set; }

        [Display(Name = "Nhân lực trong ngành CNTT Thạc sĩ")]
        public int NLTN_ThacSi { get; set; }

        [Display(Name = "Nhân lực trong ngành CNTT Khác")]
        public int NLTN_Khac { get; set; }

        [Display(Name = "Nhân lực ngoài ngành CNTT Đại Học")]
        public int NLNN_DaiHoc { get; set; }

        [Display(Name = "Nhân lực ngoài ngành CNTT Cao đẳng")]
        public int NLNN_CaoDang { get; set; }

        [Display(Name = "Nhân lực ngoài ngành CNTT Trung Cấp")]
        public int NLNN_TrungCap { get; set; }

        [Display(Name = "Nhân lực ngoài ngành CNTT Tiến sĩ")]
        public int NLNN_TienSi { get; set; }

        [Display(Name = "Nhân lực ngoài ngành CNTT Thạc sĩ")]
        public int NLNN_ThacSi { get; set; }

        [Display(Name = "Nhân lực ngoài ngành CNTT Khác")]
        public int NLNN_Khac { get; set; }
        public Nullable<int> LichNhap_ID { get; set; }
    }
}
