//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace S4T_HaTinh.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using S4T_HaTinh.App_GlobalResources;
    
    public partial class ToChucChinhSachCNTT
    {
        [Key]
        public int ToChucChinhSachCNTT_ID { get; set; }
        public int DonVi_ID { get; set; }
        public string TenVanBan { get; set; }
        public string SoKiHieu { get; set; }
        public byte Success { get; set; }
        public string TruongNhapLai { get; set; }
        public int LichNhap_ID { get; set; }
    }
}
