//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace S4T_HaTinh.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using S4T_HaTinh.App_GlobalResources;

    public partial class UngDungCNTT
    {
        [Key]
        public int UngDungCNTT_ID { get; set; }
        public int LichNhap_ID { get; set; }

        [Display(Name = "Đơn vị")]
        public int DonVi_ID { get; set; }

        [Display(Name = "Quản lý văn bản và điều hành tác nghiệp trực tuyến")]
        public byte QLVB { get; set; }

        [Display(Name = "Quản lý nhân sự")]
        public byte QLNhanSu { get; set; }

        [Display(Name = "Quản lý tài chính-kế toán")]
        public byte QLTaiChinhKeToan { get; set; }

        [Display(Name = "Tài chính kế toán và tài sản công")]
        public byte QLTaiSanCong { get; set; }

        [Display(Name = "Quản lý thanh tra, khiếu nại tố cáo")]
        public byte QLKhieuNai { get; set; }

        [Display(Name = "Ứng dụng chữ ký số")]
        public byte ChuKySo { get; set; }

        [Display(Name = "Một cửa điện tử")]
        public byte MotCuaDienTu { get; set; }

        [Display(Name = "Số TTHC được đưa vào một cửa điện tử")]
        public int SoTTHC { get; set; }

        [Display(Name = "Số đơn vị kết nối liên thông")]
        public int DV_LienThong { get; set; }

        [Display(Name = "Số văn bản đi được đưa lên phần mềm")]
        public int VBDi { get; set; }

        [Display(Name = "Số văn bản đến được đưa lên phần mềm")]
        public int VBDen { get; set; }

        [Display(Name = "Tổng số văn bản đi của cơ quan")]
        public int TongSo_VBDi { get; set; }

        [Display(Name = "Tổng số văn bản đến của cơ quan")]
        public int TongSo_VBDen { get; set; }

        [Display(Name = "Số email (mail.hatinh.gov.vn) thường xuyên sử dụng")]
        public int SoEmail { get; set; }

        [Display(Name = "Open Office")]
        public int OpenOffice { get; set; }

        [Display(Name = "Mozilla ThunderBird")]
        public int MozillaThunderBird { get; set; }

        [Display(Name = "Mozilla FireFox")]
        public int MozillaFireFox { get; set; }

        [Display(Name = "Unikey")]
        public int Unikey { get; set; }

        [Display(Name = "Hệ điều hành PMNM")]
        public int PMNM { get; set; }

        [Display(Name = "Máy chủ cài hệ điều hành PMNM")]
        public int PMNM_MayChu { get; set; }

        [Display(Name = "Tổng mức đầu tư")]
        public decimal TongMucDauTu { get; set; }

        [Display(Name = "Trạng thái")]
        public byte Success { get; set; }

        [Display(Name = "Trường nhập lại")]
        public string TruongNhapLai { get; set; }

        public List<UngDungCNTT_PMQLCN> ListPMQLCN { get; set; }
    }
}
