//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace S4T_HaTinh.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VanBan
    {
        public int VanBan_ID { get; set; }
        public int LoaiVanBan_ID { get; set; }
        public string TenVanBan { get; set; }
        public string FileUpload { get; set; }
        public int DonViBanHanh_ID { get; set; }
        public string TrichYeu { get; set; }
        public Nullable<System.DateTime> NgayTao { get; set; }
        public Nullable<System.DateTime> NgayCapNhat { get; set; }
        public byte Success { get; set; }
        public int NhomVanBan_ID { get; set; }
        public int PhienBan_ID { get; set; }
        public string SoKyHieu { get; set; }
        public Nullable<System.DateTime> NgayBanHanh { get; set; }
        public string TenFile { get; set; }
        public string TenHienThi { get; set; }
        public string DuongDan { get; set; }
        public byte TrangThai { get; set; }
        public int STT { get; set; }
        public int int1 { get; set; }
        public int int2 { get; set; }
        public int int3 { get; set; }
        public int int4 { get; set; }
        public int int5 { get; set; }
        public string str1 { get; set; }
        public string str2 { get; set; }
        public string str3 { get; set; }
        public string str4 { get; set; }
        public string str5 { get; set; }
    }
}
