//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace S4T_HaTinh.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewLichNhap_HaTangKyThuatCapHuyen
    {
        public string TenDonVi { get; set; }
        public int NhomDonVi_ID { get; set; }
        public int DonViCap1_ID { get; set; }
        public Nullable<int> SoCBCC { get; set; }
        public Nullable<int> SoCB_DVTT { get; set; }
        public Nullable<int> SoDonViTrucThuoc { get; set; }
        public Nullable<int> DotBaoCao_ID { get; set; }
        public Nullable<int> Nam { get; set; }
        public Nullable<int> ChucNang_ID { get; set; }
        public int HaTangKyThuatCNTTHuyen_ID { get; set; }
        public int LichNhap_ID { get; set; }
        public int DonVi_ID { get; set; }
        public int ADSL { get; set; }
        public int LeadedLine { get; set; }
        public int CapQuang { get; set; }
        public int Khac { get; set; }
        public int UBND_MayBan { get; set; }
        public int UBND_LapTop { get; set; }
        public int UBND_MayChu { get; set; }
        public int UBND_VirusBanQuyen { get; set; }
        public int UBND_Internet { get; set; }
        public int UBND_MangCD { get; set; }
        public int HuyenUy_MayBan { get; set; }
        public int HuyenUy_LapTop { get; set; }
        public int HuyenUy_MayChu { get; set; }
        public int HuyenUy_VirusBanQuyen { get; set; }
        public int HuyenUy_Internet { get; set; }
        public int HuyenUy_MangCD { get; set; }
        public int Xa_MayBan { get; set; }
        public int Xa_LapTop { get; set; }
        public int Xa_MayChu { get; set; }
        public int Xa_VirusBanQuyen { get; set; }
        public int Xa_Internet { get; set; }
        public int Xa_MangCD { get; set; }
        public int GiaoDuc_MayBan { get; set; }
        public int GiaoDuc_LapTop { get; set; }
        public int GiaoDuc_MayChu { get; set; }
        public int GiaoDuc_VirusBanQuyen { get; set; }
        public int GiaoDuc_Internet { get; set; }
        public int GiaoDuc_MangCD { get; set; }
        public int YTe_MayBan { get; set; }
        public int YTe_LapTop { get; set; }
        public int YTe_MayChu { get; set; }
        public int YTe_VirusBanQuyen { get; set; }
        public int YTe_Internet { get; set; }
        public int YTe_MangCD { get; set; }
        public int Khac_MayBan { get; set; }
        public int Khac_LapTop { get; set; }
        public int Khac_MayChu { get; set; }
        public int Khac_VirusBanQuyen { get; set; }
        public int Khac_Internet { get; set; }
        public int Khac_MangCD { get; set; }
        public int VHX_MayBan { get; set; }
        public int VHX_LapTop { get; set; }
        public int VHX_MayChu { get; set; }
        public int VHX_VirusBanQuyen { get; set; }
        public int VHX_Internet { get; set; }
        public int VHX_MangCD { get; set; }
        public int DoanhNghiep_MayBan { get; set; }
        public int DoanhNghiep_LapTop { get; set; }
        public int DoanhNghiep_MayChu { get; set; }
        public int DoanhNghiep_VirusBanQuyen { get; set; }
        public int DoanhNghiep_Internet { get; set; }
        public int DoanhNghiep_MangCD { get; set; }
        public int HoGiaDinh_MayBan { get; set; }
        public int HoGiaDinh_LapTop { get; set; }
        public int HoGiaDinh_MayChu { get; set; }
        public int HoGiaDinh_VirusBanQuyen { get; set; }
        public int HoGiaDinh_Internet { get; set; }
        public int HoGiaDinh_MangCD { get; set; }
        public int KhongKetNoiInternet { get; set; }
        public byte TuongLua { get; set; }
        public byte TruyCapTraiPhep { get; set; }
        public byte CanhBaoChayNo { get; set; }
        public byte ChongSet { get; set; }
        public byte BangTu { get; set; }
        public byte TuDia { get; set; }
        public byte SAN { get; set; }
        public byte NAS { get; set; }
        public byte DAS { get; set; }
        public byte RAID { get; set; }
        public int BuuDienXa { get; set; }
        public int BuuDienXa_Internet { get; set; }
        public byte HoiNghiTruyenHinhCapHuyen { get; set; }
        public int SoCuocHopCapHuyen { get; set; }
        public byte HoiNghiTruyenHinhCapXa { get; set; }
        public int SoCuocHopCapXa { get; set; }
        public decimal TongChiNganSach { get; set; }
        public decimal TongMucDauTu { get; set; }
        public string TruongNhapLai { get; set; }
        public byte Success { get; set; }
        public int BuuDienXa_DaiLyInternet { get; set; }
        public int SoHoiNghiTruyenHinhCapXa { get; set; }
    }
}
