//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace S4T_HaTinh.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewLichNhap_CongThongTinDienTuCapHuyen
    {
        public Nullable<int> DotBaoCao_ID { get; set; }
        public Nullable<int> Nam { get; set; }
        public Nullable<int> ChucNang_ID { get; set; }
        public string TenDonVi { get; set; }
        public int NhomDonVi_ID { get; set; }
        public int DonViCap1_ID { get; set; }
        public Nullable<int> SoCBCC { get; set; }
        public Nullable<int> SoDonViTrucThuoc { get; set; }
        public Nullable<int> SoCB_DVTT { get; set; }
        public int CongThongTinDienTuHuyen_ID { get; set; }
        public int LichNhap_ID { get; set; }
        public int DonVi_ID { get; set; }
        public string WebTTDT { get; set; }
        public string CongTTDT { get; set; }
        public string HeQuanTriCSDL { get; set; }
        public string CongNgheLoi { get; set; }
        public string NgonNguLapTrinh { get; set; }
        public int SoSubsiteCapXa { get; set; }
        public byte TTGT_SoDo_CoCau { get; set; }
        public byte TTGT_ChucNang_NhiemVu { get; set; }
        public byte TTGT_HinhThanh_PhatTrien { get; set; }
        public byte TTGT_ThongTinTomTat { get; set; }
        public byte TTGT_ThongTinGiaoDich { get; set; }
        public byte TTGT_ThongTinLienHe { get; set; }
        public byte TTGT_BanDoDiaGioi { get; set; }
        public byte TTGT_ThongTinThongKe { get; set; }
        public byte TanSuatCapNhat { get; set; }
        public int TTCD_TongSoVBChiDao_DonVi { get; set; }
        public int TTCD_TongSoVBChiDao_DieuHanh { get; set; }
        public byte TTCD_DangLichLamViec { get; set; }
        public byte TTTT_ChuyenTrangVBQPPL { get; set; }
        public byte TTTT_TinBai_DangTaiPL { get; set; }
        public byte CLDH_ChuyenMuc_ChienLuoc { get; set; }
        public byte CLDH_SoChienLuoc { get; set; }
        public byte CLDH_KeHoachPhatTrien { get; set; }
        public byte VBQP_ChuyenTrang_QPPL { get; set; }
        public byte VBQP_SoVBQPPL_DangTai { get; set; }
        public byte VBQP_LienKetQLVBQPPL { get; set; }
        public byte VBQP_ChoPhepTaiVBQPPL { get; set; }
        public byte TTDA_DauTu_ChuyenTrang { get; set; }
        public byte TTDA_SoDauTu_DuAnDuocDang { get; set; }
        public byte TTDA_DangTaiTTToiThieu { get; set; }
        public byte DTKH_ChuyenTrang { get; set; }
        public byte DTKH_DuocDangTai { get; set; }
        public byte GopY_ChuyenTrang { get; set; }
        public byte GopY_SoDuThaoXinYKien { get; set; }
        public byte GopY_CungCapTT { get; set; }
        public byte KTTT_ChucNangTimKiem { get; set; }
        public byte KTTT_SoDoWeb { get; set; }
        public byte KTTT_DangCauHoi_TraLoi { get; set; }
        public byte KTTT_DuLieuDacTa { get; set; }
        public byte KTTT_MaUnicode { get; set; }
        public byte KTTT_KhaNangTuongThich { get; set; }
        public byte KTTT_LienKetWeb { get; set; }
        public byte KTTT_HoTro_NguoiKhuyetTat { get; set; }
        public byte KTTT_TenMien_CongTTDT { get; set; }
        public int TongSoTTHC_DV { get; set; }
        public int TongSoDVC_Muc1 { get; set; }
        public int TongSoDVC_Muc2 { get; set; }
        public int TongSoDVC_Muc3 { get; set; }
        public byte DBNL_ThanhLap_BanBienTap { get; set; }
        public byte DBNL_BoTri_QuanTriKyThuat { get; set; }
        public byte DBNL_BoTri_XuLyDVCong { get; set; }
        public byte DBNL_TapHuan_DaoTaoCanBo { get; set; }
        public byte ATTT_DamBaoAnToanTTDuLieu { get; set; }
        public byte ATTT_XayDungGiaiPhap { get; set; }
        public byte ATTT_XDPhuongAnDuPhong { get; set; }
        public byte CongTTDT_BanHanhQuyChePhoiHop { get; set; }
        public byte CongTTDT_BanHanhQuyCheHoatDong { get; set; }
        public byte CongTTDT_BaoCaoDinhKy_Nam { get; set; }
        public byte DangTai_CapNhatThongTin { get; set; }
        public byte DangTai_NoiDungThongTin { get; set; }
        public byte DangTai_QuyDinhKhac { get; set; }
        public int TongSoDVTT_CoCongTTDT { get; set; }
        public int SoDNSXKD_PhanCung { get; set; }
        public int SoDNSXKD_PhanMem { get; set; }
        public int SoDNCungCapDVNDSo { get; set; }
        public string DanhSachDNCNTT_DT { get; set; }
        public decimal TongDoanhThu { get; set; }
        public decimal TongMucDauTu { get; set; }
        public string TruongNhapLai { get; set; }
        public byte Success { get; set; }
    }
}
