//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace S4T_HaTinh.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewLichNhap_HaTangNhanLuc
    {
        public int HaTangNhanLucCNTT_ID { get; set; }
        public int LichNhap_ID { get; set; }
        public int DonVi_ID { get; set; }
        public int TienSy_DV { get; set; }
        public int ThacSy_DV { get; set; }
        public int DaiHocChinhQuy_DV { get; set; }
        public int DaiHocKhongChinhQuy_DV { get; set; }
        public int LuotTapHuan_DV { get; set; }
        public int SoLuongCanBo_DV { get; set; }
        public int TienSy_DVTT { get; set; }
        public int ThacSy_DVTT { get; set; }
        public int DaiHocChinhQuy_DVTT { get; set; }
        public int DaiHocKhongChinhQuy_DVTT { get; set; }
        public int LuotTapHuan_DVTT { get; set; }
        public int SoLuongCanBo_DVTT { get; set; }
        public int ThanhThaoMayTinh_DV { get; set; }
        public int LuotTapHuanThanhThaoMayTinh_DV { get; set; }
        public int ThanhThaoMayTinh_DVTT { get; set; }
        public int LuotTapHuanThanhThaoMayTinh_DVTT { get; set; }
        public byte Success { get; set; }
        public string TruongNhapLai { get; set; }
        public Nullable<int> DotBaoCao_ID { get; set; }
        public Nullable<int> Nam { get; set; }
        public Nullable<int> ChucNang_ID { get; set; }
        public string TenDonVi { get; set; }
        public int NhomDonVi_ID { get; set; }
        public int DonViCap1_ID { get; set; }
        public decimal TongMucDauTu { get; set; }
        public Nullable<int> SoCBCC { get; set; }
        public Nullable<int> SoDonViTrucThuoc { get; set; }
        public Nullable<int> SoCB_DVTT { get; set; }
    }
}
