//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace S4T_HaTinh.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewLichNhap_HaTangNhanLucCapHuyen
    {
        public string TenDonVi { get; set; }
        public int NhomDonVi_ID { get; set; }
        public int DonViCap1_ID { get; set; }
        public Nullable<int> SoCBCC { get; set; }
        public Nullable<int> SoDonViTrucThuoc { get; set; }
        public Nullable<int> SoCB_DVTT { get; set; }
        public Nullable<int> DotBaoCao_ID { get; set; }
        public Nullable<int> Nam { get; set; }
        public Nullable<int> ChucNang_ID { get; set; }
        public int HaTangNhanLucCNTTHuyen_ID { get; set; }
        public int LichNhap_ID { get; set; }
        public int DonVi_ID { get; set; }
        public int TieuHoc_SoTruong { get; set; }
        public int TieuHoc_TinHoc { get; set; }
        public int TieuHoc_NganhCNTT { get; set; }
        public int TieuHoc_KhoaCNTT { get; set; }
        public int TieuHoc_GVCNTT { get; set; }
        public int TieuHoc_TSCNTT { get; set; }
        public int TieuHoc_ThSCNTT { get; set; }
        public int TieuHoc_SVCNTT { get; set; }
        public int THCS_SoTruong { get; set; }
        public int THCS_TinHoc { get; set; }
        public int THCS_NganhCNTT { get; set; }
        public int THCS_KhoaCNTT { get; set; }
        public int THCS_GVCNTT { get; set; }
        public int THCS_TSCNTT { get; set; }
        public int THCS_ThSCNTT { get; set; }
        public int THCS_SVCNTT { get; set; }
        public int THPT_SoTruong { get; set; }
        public int THPT_TinHoc { get; set; }
        public int THPT_NganhCNTT { get; set; }
        public int THPT_KhoaCNTT { get; set; }
        public int THPT_GVCNTT { get; set; }
        public int THPT_TSCNTT { get; set; }
        public int THPT_ThSCNTT { get; set; }
        public int THPT_SVCNTT { get; set; }
        public int TrungCap_SoTruong { get; set; }
        public int TrungCap_TinHoc { get; set; }
        public int TrungCap_NganhCNTT { get; set; }
        public int TrungCap_KhoaCNTT { get; set; }
        public int TrungCap_GVCNTT { get; set; }
        public int TrungCap_TSCNTT { get; set; }
        public int TrungCap_ThSCNTT { get; set; }
        public int TrungCap_SVCNTT { get; set; }
        public int CaoDang_SoTruong { get; set; }
        public int CaoDang_MonTinHoc { get; set; }
        public int CaoDang_NganhCNTT { get; set; }
        public int CaoDang_KhoaCNTT { get; set; }
        public int CaoDang_GVCNTT { get; set; }
        public int CaoDang_TSCNTT { get; set; }
        public int CaoDang_ThSCNTT { get; set; }
        public int CaoDang_SVCNTT { get; set; }
        public int DaiHoc_SoTruong { get; set; }
        public int DaiHoc_MonTinHoc { get; set; }
        public int DaiHoc_NganhCNTT { get; set; }
        public int DaiHoc_KhoaCNTT { get; set; }
        public int DaiHoc_GVCNTT { get; set; }
        public int DaiHoc_TSCNTT { get; set; }
        public int DaiHoc_ThSCNTT { get; set; }
        public int DaiHoc_SVCNTT { get; set; }
        public int Khac_SoTruong { get; set; }
        public int Khac_MonTinHoc { get; set; }
        public int Khac_NganhCNTT { get; set; }
        public int Khac_KhoaCNTT { get; set; }
        public int Khac_GVCNTT { get; set; }
        public int Khac_TSCNTT { get; set; }
        public int Khac_ThSCNTT { get; set; }
        public int Khac_SVCNTT { get; set; }
        public int CBCT_Huyen_SoLuong { get; set; }
        public int CBCT_Huyen_TienSy { get; set; }
        public int CBCT_Huyen_ThacSy { get; set; }
        public int CBCT_Huyen_DHCQ { get; set; }
        public int CBCT_Huyen_DHKhongCQ { get; set; }
        public int CBCT_Huyen_HocThacSy { get; set; }
        public int CBCT_Huyen_NghienCuuSinh { get; set; }
        public int CBCT_Huyen_LuotTapHuan { get; set; }
        public int CBCT_Xa_SoLuong { get; set; }
        public int CBCT_Xa_TienSy { get; set; }
        public int CBCT_Xa_ThacSy { get; set; }
        public int CBCT_Xa_DHCQ { get; set; }
        public int CBCT_Xa_DHKhongCQ { get; set; }
        public int CBCT_Xa_HocThacSy { get; set; }
        public int CBCT_Xa_NghienCuuSinh { get; set; }
        public int CBCT_Xa_LuotTapHuan { get; set; }
        public int UBND_ThanhThao { get; set; }
        public int UBND_ThamGiaTapHuan { get; set; }
        public int UBND_TSCNTT { get; set; }
        public int UBND_ThSCNTT { get; set; }
        public int UBND_HocThacSy { get; set; }
        public int UBND_NghienCuuSinh { get; set; }
        public int HuyenUy_ThanhThao { get; set; }
        public int HuyenUy_LuotTapHuan { get; set; }
        public int HuyenUy_TSCNTT { get; set; }
        public int HuyenUy_ThSCNTT { get; set; }
        public int HuyenUy_HocThacSy { get; set; }
        public int HuyenUy_NghienCuuSinh { get; set; }
        public int Xa_ThanhThao { get; set; }
        public int Xa_LuotTapHuan { get; set; }
        public int Xa_TSCNTT { get; set; }
        public int Xa_ThSCNTT { get; set; }
        public int Xa_HocThacSy { get; set; }
        public int Xa_NghienCuuSinh { get; set; }
        public int GiaoDuc_ThanhThao { get; set; }
        public int GiaoDuc_LuotTapHuan { get; set; }
        public int GiaoDuc_TSCNTT { get; set; }
        public int GiaoDuc_ThSCNTT { get; set; }
        public int GiaoDuc_HocThacSy { get; set; }
        public int GiaoDuc_NghienCuuSinh { get; set; }
        public int YTe_ThanhThao { get; set; }
        public int YTe_LuotTapHuan { get; set; }
        public int YTe_TSCNTT { get; set; }
        public int YTe_ThSCNTT { get; set; }
        public int YTe_HocThacSy { get; set; }
        public int YTe_NghienCuuSinh { get; set; }
        public int DVSN_ThanhThao { get; set; }
        public int DVSN_LuotTapHuan { get; set; }
        public int DVSN_TSCNTT { get; set; }
        public int DVSN_ThSCNTT { get; set; }
        public int DVSN_HocThacSy { get; set; }
        public int DVSN_NghienCuuSinh { get; set; }
        public int DN_ThanhThao { get; set; }
        public int DN_LuotTapHuan { get; set; }
        public int DN_TSCNTT { get; set; }
        public int DN_ThSCNTT { get; set; }
        public int DN_HocThacSy { get; set; }
        public int DN_NghienCuuSinh { get; set; }
        public int CBCCVC_Khac_ThanhThao { get; set; }
        public int CBCCVC_Khac_LuotTapHuan { get; set; }
        public int CBCCVC_Khac_TSCNTT { get; set; }
        public int CBCCVC_Khac_ThSCNTT { get; set; }
        public int CBCCVC_Khac_HocThacSy { get; set; }
        public int CBCCVC_Khac_NghienCuuSinh { get; set; }
        public decimal TongChiNganSach { get; set; }
        public decimal TongMucDauTu { get; set; }
        public string TruongNhapLai { get; set; }
        public byte Success { get; set; }
    }
}
